# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "ThisLittlePiggy" do
pod 'GDataXML-HTML', '~> 1.1.0'
end

target "ThisLittlePiggyTests" do

end

target "ThisLittlePiggyLevelEditor" do
pod 'GDataXML-HTML', '~> 1.1.0'
end

target "ThisLittlePiggyLevelEditorTests" do

end
